# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maxpavlovdp/aws-cli-node4.5.0

pipelines:
  default:
    - step:
        script: # build and test
          - cd ./webapp
          - npm install
          - npm install webpack -g
          - webpack -p
          - export CI=true
          - npm test -- --coverage
  branches:
    master:
      - step:
           script: # Deploy to git hub pages https://maxpavlovdp.github.io/jetaudio/#/
           - cd ./webapp
           - ./buildAndDeployMaster.sh
    BOOST-108_MouseBehaviour:
      - step:
          script: # Deploy to aws s3 https://s3.eu-central-1.amazonaws.com/zas-on-demand-branch/index.html
           - cd ./webapp
           - npm install
           - npm install webpack -g
           - webpack -p
           - export CI=true
           - npm test -- --coverage
           - cp ./src/config/prodConfig.js ./public/config.js
           - ./deploy-to-s3/deployToS3OnDemandBucket.sh
    BOOST-98_soundDesignDevelopment:
      - step:
          script: # Deploy to aws s3 https://s3.eu-central-1.amazonaws.com/zas-boost-98-branch/index.html
           - cd ./webapp
           - npm install
           - npm install webpack -g
           - webpack -p
           - export CI=true
           - npm test -- --coverage
           - cp ./src/config/prodConfig.js ./public/config.js
           - ./deploy-to-s3/deployToS3Boost-98Bucket.sh
    develop:
      - step:
          script: # Deploy to aws s3 https://s3.eu-central-1.amazonaws.com/zas-develop-branch/index.html
           - cd ./webapp
           - npm install
           - npm install webpack -g
           - webpack -p
           - export CI=true
           - npm test -- --coverage
           - cp ./src/config/devConfig.js ./public/config.js
           - ./deploy-to-s3/deployToS3DevelopBucket.sh
