# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maxpavlovdp/aws-cli-node4.5.0

pipelines:
  default:
    - step:
        script: # build and test
          - cd ./webapp
          - npm install
          - npm install webpack -g
          - webpack -p
          - npm test
  branches:
    BOOST-151_DeployToS3:
      - step:
          script: # Deploy to aws s3
           - cd ./webapp
#           - npm install
#           - npm install webpack -g
#           - webpack -p
           - ./deploy-to-s3/deployToS3Develop.sh